# Generated by Django 4.2.13 on 2024-06-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMesaAyuda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userTipo',
            field=models.CharField(choices=[('Administrativo', 'Administrativo'), ('Instructor', 'Instructor'), ('Tecnico', 'Tecnico')], db_comment='Tipo de usuario', max_length=15),
        ),
    ]
